/* eslint-disable */
// This file is automatically generated by OneAPI, please do not modify it manually!

import * as CategoryController from './category/CategoryController';
import * as TagController from './tag/TagController';
import * as PostController from './post/PostController';
import * as FileController from './file/FileController';
export default {
  CategoryController,
  FileController,
  TagController,
  PostController
};

